services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-energy_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mailpit
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-django-insecure-secret}
      - POSTGRES_DB=${POSTGRES_DB:-energy_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_HOST=${EMAIL_HOST:-mailpit}
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-from@example.com}

  celery_worker:
    build: 
     context: ./api
     dockerfile: Dockerfile
    command: celery -A energy_approval worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - api
      - mailpit
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-django-insecure-secret}
      - POSTGRES_DB=${POSTGRES_DB:-energy_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_HOST=${EMAIL_HOST:-mailpit}
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-from@example.com}

  celery_beat:
    build:
     context: ./api
     dockerfile: Dockerfile
    command: celery -A energy_approval beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - api
      - mailpit
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-django-insecure-secret}
      - POSTGRES_DB=${POSTGRES_DB:-energy_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_HOST=${EMAIL_HOST:-mailpit}
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-from@example.com}

volumes:
  postgres_data:
  mailpit_data:
